"""
policyswarm.network
===================
Social network topology constructors.

Two topologies are supported:

  Barabási–Albert (BA)
      Scale-free network generated by preferential attachment (Iteration 3).
      Produces heavy-tailed degree distributions; a small number of hub agents
      dominate opinion propagation. Models large social platforms.

  Stochastic Block Model (SBM)
      Community-structured graph (Iteration 7). Within-community edge
      probability is 10× cross-community probability, producing echo-chamber
      dynamics that are visible as isolated clusters in the opinion scatter.

Both builders return a NetworkX graph plus a pre-computed influence array
aligned with agent indices 0..n-1.
"""

from __future__ import annotations

from typing import Dict, List, Tuple
import numpy as np
import networkx as nx

from .config import NetworkType, SimConfig


# ---------------------------------------------------------------------------
# Barabási–Albert
# ---------------------------------------------------------------------------

def build_barabasi_albert(
    n    : int,
    m    : int  = 3,
    seed : int  = 0,
) -> nx.Graph:
    """Construct a scale-free network via preferential attachment.

    Parameters
    ----------
    n : int
        Number of nodes.
    m : int
        Number of edges added per new node. Default 3.
    seed : int
        Random seed for reproducibility. Default 0.

    Returns
    -------
    networkx.Graph
        Undirected BA graph with ``n`` nodes.
    """
    return nx.barabasi_albert_graph(n, m, seed=seed)


# ---------------------------------------------------------------------------
# Stochastic Block Model
# ---------------------------------------------------------------------------

def build_stochastic_block_model(
    n              : int,
    n_communities  : int   = 3,
    p_in           : float = 0.20,
    p_out          : float = 0.02,
    seed           : int   = 0,
) -> Tuple[nx.Graph, np.ndarray]:
    """Construct a community-structured network via the SBM.

    Parameters
    ----------
    n : int
        Total number of nodes.
    n_communities : int
        Number of blocks (communities). Default 3.
    p_in : float
        Within-community edge probability. Default 0.20.
    p_out : float
        Cross-community edge probability. Default 0.02.
        A 10:1 p_in/p_out ratio produces visible echo-chamber structure.
    seed : int
        Random seed. Default 0.

    Returns
    -------
    graph : networkx.Graph
    community_labels : np.ndarray, shape (n,), dtype int
        Community membership for each agent.
    """
    rng = np.random.default_rng(seed)
    # Distribute agents roughly evenly across communities
    base, rem = divmod(n, n_communities)
    sizes = [base + (1 if i < rem else 0) for i in range(n_communities)]

    probs = [
        [p_in if i == j else p_out for j in range(n_communities)]
        for i in range(n_communities)
    ]

    G = nx.stochastic_block_model(sizes, probs, seed=seed)

    # Build community label array aligned to node indices
    labels = np.empty(n, dtype=int)
    start = 0
    for community_id, size in enumerate(sizes):
        labels[start : start + size] = community_id
        start += size

    return G, labels


# ---------------------------------------------------------------------------
# Influence computation
# ---------------------------------------------------------------------------

def compute_influence(graph: nx.Graph) -> np.ndarray:
    """Compute normalised degree-based influence scores.

    Maps network degree to agent influence in [0, 1].  This grounds
    "influence" in structural network position rather than assigning it
    arbitrarily (Iteration 3 design note).

    The maximum degree is used as the denominator; a small epsilon prevents
    division by zero on isolated-node graphs.

    Parameters
    ----------
    graph : networkx.Graph

    Returns
    -------
    np.ndarray, shape (n,)
        Normalised influence scores in [0, 1].
    """
    n = graph.number_of_nodes()
    degrees = np.array([graph.degree(i) for i in range(n)], dtype=float)
    max_deg = degrees.max()
    if max_deg < 1e-9:
        return np.ones(n) * 0.5
    return degrees / (max_deg + 1e-9)


def top_hub_indices(graph: nx.Graph, k: int = 10) -> List[int]:
    """Return indices of the k highest-degree nodes.

    Used by the hub-targeted shock mechanism (Iteration 10/11).

    Parameters
    ----------
    graph : networkx.Graph
    k : int
        Number of hubs to return. Default 10.

    Returns
    -------
    list of int
    """
    degree_seq = sorted(graph.degree, key=lambda x: x[1], reverse=True)
    return [node for node, _ in degree_seq[:k]]


# ---------------------------------------------------------------------------
# Factory dispatcher
# ---------------------------------------------------------------------------

def build_network(
    config          : SimConfig,
    seed            : int = 0,
) -> Tuple[nx.Graph, np.ndarray, np.ndarray]:
    """Factory: construct the appropriate network given SimConfig.

    Parameters
    ----------
    config : SimConfig
    seed : int

    Returns
    -------
    graph : networkx.Graph
    influence : np.ndarray, shape (n_agents,)
        Normalised degree-based influence.
    community_labels : np.ndarray, shape (n_agents,)
        Community membership. All zeros for BA graphs.
    """
    n = config.n_agents

    if config.network_type == NetworkType.BARABASI_ALBERT:
        graph = build_barabasi_albert(n, m=config.ba_m, seed=seed)
        community_labels = np.zeros(n, dtype=int)
    elif config.network_type == NetworkType.STOCHASTIC_BLOCK:
        graph, community_labels = build_stochastic_block_model(
            n,
            n_communities = config.sbm_n_communities,
            p_in          = config.sbm_p_in,
            p_out         = config.sbm_p_out,
            seed          = seed,
        )
    else:
        raise ValueError(f"Unknown network type: {config.network_type}")

    influence = compute_influence(graph)
    return graph, influence, community_labels


# ---------------------------------------------------------------------------
# Neighbour cache
# ---------------------------------------------------------------------------

def build_neighbour_cache(graph: nx.Graph) -> Dict[int, List[int]]:
    """Pre-compute adjacency lists for O(1) neighbour lookup during simulation.

    Parameters
    ----------
    graph : networkx.Graph

    Returns
    -------
    dict mapping node index → list of neighbour indices
    """
    return {i: list(graph.neighbors(i)) for i in graph.nodes()}
